### ISSUE TITLE
ISSUE-22: add opendkim.libfeature() interface

### ISSUE THREAD

**Issue by godsflaw** [godsflaw/node-opendkim#22]
It is common to check for compiled lib features like `DKIM_FEATURE_SHA256`.  We need to add the `opendkim.libfeature()` interface, tests, and documentation.

- [x] code
- [x] tests
- [x] documentation

For a good example of the above items see: https://github.com/godsflaw/node-opendkim/pull/33
Note that the first commit title should start with `ISSUE-22:`

more information:
http://www.opendkim.org/libopendkim/dkim_libfeature.html

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=50011644)](https://www.bountysource.com/issues/50011644-issue-22-add-opendkim-libfeature-interface?utm_source=50011644&utm_medium=shield&utm_campaign=ISSUE_BADGE)
https://ethlance.com/#/job/226

**Comment by leroycep** [comment]
Hey, I'm working on this issue, and I'm wondering what you want the API to look like. It requires an object to be passed in at the moment:

```
opendkim.lib_feature({feature: 'DKIM_FEATURE_DIFFHEADERS'});
```

I'm thinking that I will remove the object around the string.

Do you want to use some int constants instead of strings? That's how the original library did it, but I doubt that there is a need for integer's here, as the function only allows queries for one value anyway.

**Comment by godsflaw** [comment]
Oh, yeah, interesting.  So for the options interface I started creating getters and setters for each feature.  This was fairly quick, since a bunch of the code is in javascript:
https://github.com/godsflaw/node-opendkim/blob/dev/index.js

and then I had two addon methods for set/get.

We should probably make an addon `set_feature()` like:
https://github.com/godsflaw/node-opendkim/blob/dev/src/opendkim.cc#L677-L758

and an addon `get_feature` like:
https://github.com/godsflaw/node-opendkim/blob/dev/src/opendkim.cc#L609-L675

This would make implementation a fairly straight forward copy/paste and change some code.  I'm open to other ideas though.  Thoughts?

**Comment by godsflaw** [comment]
@Geemili ^^^

**Comment by leroycep** [comment]
My first thought is that the `dkim_libfeature()` API doesn't really match the Option API? `libfeature()` only lets you check the underlying library for a feature.

My current ideas for the function are as follows.

```
opendkim.lib_feature({feature: 'DKIM_FEATURE_DIFFHEADERS'});
opendkim.lib_feature('DKIM_FEATURE_DIFFHEADERS');
opendkim.lib_feature_diffheaders();
```

Option 2 is what I'm aiming to implement.

**Comment by godsflaw** [comment]
@Geemili yeah, I like the second option too, go for it. 
 `opendkim.lib_feature('DKIM_FEATURE_DIFFHEADERS');`
