### ISSUE TITLE
ISSUE-49: add contributing/issue/pull templates to this repo

### ISSUE THREAD

**Issue by godsflaw** [godsflaw/node-opendkim#49]
Follow the instructions here, and make contributing/issue/pull templates in the `.github` directory:

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by desttinghim** [comment]
Can this issue be closed? It looks like you have already added the templates.

**Comment by godsflaw** [comment]
Yes, it can, thanks @desttinghim
