### ISSUE TITLE
ISSUE-51: implement opendkim.ohdrs()

### ISSUE THREAD

**Issue by godsflaw** [godsflaw/node-opendkim#51]
Implement `opendkim.ohdrs()` for getting the original headers signed by the signature.  This will be useful with `opendkim.diffheaders()`.

- [ ] code
- [ ] tests
- [ ] documentation

For a good example of the above items see: https://github.com/godsflaw/node-opendkim/pull/33
Note that the first commit title should start with `ISSUE-51:`

more information:
http://www.opendkim.org/libopendkim/dkim_ohdrs.html

Bounty:
https://ethlance.com/#/job/241

**Comment by desttinghim** [comment]
Does this go under the Administration, Processing, Signing, or Utility section?
EDIT: Looks like it goes under Verifying in the documentation, which isn't being used by us yet. Should I add that section?
EDIT2: Never mind it seems that I am blind.

What values should we be returning? I imagine we would want to return the contents of the `ptrs` variable. 

Additionally, we need a test message with the `z=` tag. I don't quite know what I would need to do to make this.

**Comment by godsflaw** [comment]
@desttinghim, I think I can create the `z=` header.  I extracted a bunch of the test messages from the original opendkim library, and I can see there is a test message in there with `z=`.  I'll try to merge up a test message with `z=` sometime tomorrow.

As for the headers, yes, we need to make an array of headers to return back to the caller:
```
v8::Local<v8::Array> zheaders = Nan::New<v8::Array>(pcnt);
for (int i = 0; i < pcnt; i++ ) {
  Nan::Set(zheaders, i, Nan::New(Nan::New<v8::String>(ptrs[i]).ToLocalChecked()));
}
info.GetReturnValue().Set(zheaders);
```

I'm not sure if this code works, it's off the top of my head.  I think it will get you close.

**Comment by godsflaw** [comment]
I created #63 so that we have a valid message with `z=` data in the header.  Once #64 is merged, it will be right on `dev`.
