### ISSUE TITLE
ISSUE-61: implement opendkim.sig_getcanonlen()

### ISSUE THREAD

**Issue by godsflaw** [godsflaw/node-opendkim#61]
# Description

Implement `opendkim.sig_getcanonlen()`.  Documentation on this object will be important.  The node.js interface for this function should return an object of the form:
```
{
  "msglen": 512,
  "canonlen": 256,
  "signlen": -1
} 
```

# PR must contain

* a first commit title that starts with 'ISSUE-61:'
* code
* tests
* documentation

# Example PR
https://github.com/godsflaw/node-opendkim/pull/50

# More Information
http://www.opendkim.org/libopendkim/dkim_sig_getcanonlen.html

# Bounty
https://ethlance.com/#/job/252

**Comment by bhenze** [comment]
Hi there, I just found this bounty in Ethlance and am available to dig in. I just wanted to make sure the bounty is still valid since it was posted a few months back. If it is still valid I would be happy to assist.

**Comment by godsflaw** [comment]
@bhenze sorry for the delay in response.  Yes, this issue is still available on ethlance for bounty.  Send a proposal through ethlance and I'll accept it.  I look forward to working with you.

**Comment by bhenze** [comment]
@hodsflaw Awesome. I will set it over and start working on it in the morning.

**Comment by bhenze** [comment]
@godsflaw sorry I didn't get back to you until now. I just submitted a proposal through Ethlance. I have everything building and will work on making updates later this evening.

**Comment by godsflaw** [comment]
@bhenze great, I accepted your proposal on ethlance.  Thanks for the help.

**Comment by bhenze** [comment]
@godsflaw I think my changes are ready to go and I am trying to put a pull request together but it appears I do not have access to create a branch. Getting the following when I try to push the ISSUE-61 branch I created:

ERROR: Permission to godsflaw/node-opendkim.git denied to bhenze.

**Comment by godsflaw** [comment]
@bhenze All you have to do is:
 ```
1. fork this repo
2. change this repo's remote name to be upstream:
    git remote rename origin upstream
3. add your new fork as a remote:
    git remote add origin git@github.com:bhenze/node-opendkim.git
4. update all your remotes for good measure:
    git remote update
5. push your branch to your fork with:
    git push origin <branch_name>
6. go to your github fork (https://github.com/bhenze/node-opendkim)
7. click on the green pull request button to PR it against this repo
```

**Comment by bhenze** [comment]
Awesome! Thanks for the info. Should have this ready in the next few hours.

**Comment by bhenze** [comment]
Two quick questions. First, how do I update the wiki? Also, was wanting to test different message lengths. In particular, I wanted to see the difference between relaxed and simple canonicalization and the signature length limit. Do you have a simple way to generate the message emls?

**Comment by godsflaw** [comment]
So, for the documentation you can just put the text in a gist and include that in the PR.  I'll copy it over to the wiki.

As for the messages, there are a bunch of messages I ported over from the C source, but it's still a very manual process for me to sign a new message so we can verify it.  This would be a good tool at some point, but I've not completed most of the signing code yet.

If you have a few messages, you can link them in a gist and I'll see if I can make a new signed message that represents them (with the C source).  Or you can just push what you have and it might be good enough without the extra tests.

**Comment by bhenze** [comment]
Awesome, that sounds good. I think the basic test is probably good enough since the objective probably isn't to test opendkim but the wrapper calling it. I need to run to an event but will publish my PR in a bit.

**Comment by bhenze** [comment]
https://github.com/godsflaw/node-opendkim/pull/66
